### ISSUE TITLE
llvm version

### ISSUE THREAD

**Issue by tiopex** [directfb2/SwiftShaderGL-DirectFB#3]
Which version of llvm should be used to compile this project?

**Comment by caramelli** [comment]
For my part, I only tested it with LLVM-10.0.1 which is now a bit old.

**Comment by tiopex** [comment]
Thanks, it compiles with this version, but it hangs. What version of Mesa should it be?

**Comment by caramelli** [comment]
Mesa provides an implementation of OpenGL ES 2.0 (among others, since OpenGL or Vulkan implementations are also available in Mesa), and EGL for various platforms (X11, Wayland, ...).

SwiftShaderGL-DirectFB has no link with Mesa, it is another implementation of the OpenGL ES 2.0 and EGL standards defined by the Khronos Group but for the DirectFB platform only.

Your application should therefore use EGL API with a DirectFB surface as native window.
For example, you can test the libEGL.so.1 and libGLESv2.so.2 libraries from SwiftShaderGL-DirectFB with [yagears](https://github.com/caramelli/yagears):

	yagears2 -b egl-directfb -e glesv2

**Comment by caramelli** [comment]
Note that if you can successfully run yagears2 with the SwiftShader-OpenGL libraries, then you should be able to build SDL2 with DirectFB and OpenGL support. This allows running SDL2-based OpenGL applications on top of DirectFB.

**Comment by tiopex** [comment]
Im testing with `yagears2 -b egl-directfb -e glesv2` but glCreateProgram returns 0

**Comment by caramelli** [comment]
What is the output of:

	strace yagears2 -b egl-directfb -e glesv2

**Comment by tiopex** [comment]
strace: [out.txt](https://github.com/user-attachments/files/17648098/out.txt)

**Comment by caramelli** [comment]
OK, you can see open("/usr/lib/libGL.so.1", O_RDONLY) = 4,  which is incorrect.

I don't know which implementation this libGL.so.1 comes from (maybe Mesa), but mixing the SwiftShaderGL-DirectFB implementation with another cannot work.

Can you check the output of ldd yagears2? If libGL.so.1 is present, rebuild yagears2 by setting -Dgl=false in the meson setup

Then on your target, make sure that /usr/lib/libEGL.so.1 and /usr/lib/libGLESv2.so.2 are the libraries coming from SwiftShaderGL-DirectFB

**Comment by tiopex** [comment]
Yes, it was from Mesa. After setting` -Dgl=false`, it started, but nothing is visible except the DFB mouse cursor.

**Comment by caramelli** [comment]
I assume DirectFB examples such as df_andi work fine.

When you run yagears2 you should get messages like this on your console:

   ~~~~~~~~~~~~~~~~~~~~~~~~~~| DirectFB 2.0.0  |~~~~~~~~~~~~~~~~~~~~~~~~~~
        (c) 2017-2023  DirectFB2 Open Source Project (fork of DirectFB)
        (c) 2012-2016  DirectFB integrated media GmbH
        (c) 2001-2016  The world wide DirectFB Open Source Community
        (c) 2000-2004  Convergence (integrated media) GmbH
      ----------------------------------------------------------------

(*) DirectFB/Core: Single Application Core. (2024-11-06 15:11)

...

Gears demo: 209.04 fps
OpenGL ES 3.0 SwiftShader 4.1
OpenGL ES GLSL ES 3.00 SwiftShader 4.1
EGL 1.4 (depth 16, red 8, green 8, blue 8, alpha 0)

Can you share it?

**Comment by tiopex** [comment]
output:
```
   ~~~~~~~~~~~~~~~~~~~~~~~~~~| DirectFB 2.0.0  |~~~~~~~~~~~~~~~~~~~~~~~~~~
        (c) 2017-2023  DirectFB2 Open Source Project (fork of DirectFB)
        (c) 2012-2016  DirectFB integrated media GmbH
        (c) 2001-2016  The world wide DirectFB Open Source Community
        (c) 2000-2004  Convergence (integrated media) GmbH
      ----------------------------------------------------------------

(*) DirectFB/Core: Multi Application Core. (2024-11-06 11:41) 
(*) Fusion/SHM: Using MADV_REMOVE
(*) FBDev/System: Using device /dev/fb0 (default)
(*) FBDev/System: Found 'ST7789S-fb' (ID 0) with framebuffer at 0x80900000, 604k (MMIO 0x00000000, 0k)
(*) DirectFB/Input: miyoo_keypad 0.1 (DirectFB)
(*) DirectFB/Input: Hot-plug detection enabled with Linux Input
(*) DirectFB/Graphics: Genefx Software Rasterizer 0.7 (DirectFB)
(*) FBDev/Screen: Default mode is 320x240 (1 modes in total)
(*) DirectFB/Core/WM: Default 0.3 (DirectFB)
(*) FBDev/Mode: Setting 320x240 RGB16
(*) FBDev/Mode: Switched to 320x240 (virtual 320x240) at 16 bits (RGB16), pitch 640
(*) FBDev/Mode: Setting 320x240 RGB16
(*) FBDev/Mode: Switched to 320x240 (virtual 320x240) at 16 bits (RGB16), pitch 640
```

`df_gears` with `portableGL` works fine. I also tried simple sdl2 app with gles2, and the same behaviour, black screen with only mouse cursor

**Comment by caramelli** [comment]
This looks good.

The Escape key allows to exit yagears, you can probably map a button to exit yagears and get the following messages:

Gears demo: ???.?? fps
OpenGL ES 3.0 SwiftShader 4.1
OpenGL ES GLSL ES 3.00 SwiftShader 4.1
EGL 1.4 (depth 16, red 8, green 8, blue 8, alpha 0)

In SwiftShaderGL-DirectFB/src/Main/FrameBufferDirectFB.cpp, you can try to modify:

	void FrameBufferDirectFB::blit(sw::Surface *source, const Rect *sourceRect, const Rect *destRect)
	{
	  copy(source);
	
	  if (!(caps & DSCAPS_GL))
	    surface->Flip(surface, NULL, DSFLIP_WAITFORSYNC);
	}

with the following:

	void FrameBufferDirectFB::blit(sw::Surface *source, const Rect *sourceRect, const Rect *destRect)
	{
	  copy(source);
	
	  static int fd = 0;
	  static void *dest = NULL;
	  if (!fd)
	  {
	    fd = open("/dev/fb0", O_RDWR);
	    dest = mmap(NULL, height * stride, PROT_WRITE, MAP_SHARED, fd, 0);
	  }
	  void *src = source->lockInternal(0, 0, 0, sw::LOCK_READONLY, sw::PUBLIC);
	  memcpy(dest, src, height * stride);
	  source->unlockInternal();
	
	  if(!(caps & DSCAPS_GL))
	    surface->Flip(surface, NULL, DSFLIP_WAITFORSYNC);
	}

**Comment by tiopex** [comment]
No change after adding this code to the FrameBufferDirectFB. 

When I press ESC nothing happens

**Comment by caramelli** [comment]
Just to be sure:
* you are now able to exit yagears (OpenGL ES 3.0 SwiftShader 4.1 is printed on the console)
* memcpy(dest, src, height * stride); => you still get a black screen with DirectFB mouse cursor

Try to replace the memcpy() by:

	memset(dest, 0xFF, height * stride);
	printf("white screen\n");

This should help us understand.

**Comment by tiopex** [comment]
> Just to be sure:
> 
> * you are now able to exit yagears (OpenGL ES 3.0 SwiftShader 4.1 is printed on the console)

nope, I can only kill the app with sigkill, sigterm produces such log in console, but the process is still alive:
```
(=) [SigHandler       451.313,181] (  298) Direct/Signals:             [../lib/direct/os/linux/signals.c:283 in show_any()]   --> Caught signal 15 (sent by pid 250, uid 0) <--
(=) [SigHandler       451.549,910] (  298) Direct/Signals:             [../lib/direct/os/linux/signals.c:319 in call_handlers()]   --> -1
(!) Direct/Thread/Init: Canceling 'Fusion Dispatch' (299)!
```

> * memcpy(dest, src, height * stride); => you still get a black screen with DirectFB mouse cursor
> 
> Try to replace the memcpy() by:
> 
> ```
> memset(dest, 0xFF, height * stride);
> printf("white screen\n");
> ```

no change, no white color nor print in console, so this code is not executed

**Comment by caramelli** [comment]
OK, so this is where we need to focus, getting this printf() to display on the console!

In your out.txt file from strace, /usr/lib/libGLESv2.so.2 and /usr/lib/libEGL.so.1 are used: make sure these are the SwiftShaderGL-DirectFB libraries with the call to printf()

In SwiftShaderGL-DirectFB/src/OpenGL/libEGL/libEGL.cpp, you can add printf("GetPlatformDisplay\n"); when entering in the GetPlatformDisplay() function: this is one of the first initialization functions called when using SwiftShaderGL-DirectFB

**Comment by caramelli** [comment]
Also to be sure: with ldd yagears2, you should see libEGL.so.1  and not libGL.so.1

**Comment by tiopex** [comment]
I did some debugging and found that the code hangs on `draw(type, 0, primitiveCount);` function in `Device.cpp` from SwiftShaderGL-DirectFB
```
void Device::drawPrimitive(sw::DrawType type, unsigned int primitiveCount)
{
	if(!bindResources() || !primitiveCount)
	{
		return;
	}

	setIndexBuffer(nullptr);
	printf("beforeDraw\n");
	draw(type, 0, primitiveCount);
	printf("afterDraw\n");
}
```

in console only `beforeDraw` in printed

EDIT:

it stuck on these lines from VertexProcessor.cpp
```
generator->generate();
routine = (*generator)("VertexRoutine_%0.8X", state.shaderID);

**Comment by tiopex** [comment]
I think the lack of HW resources is the root cause here, thank you for your help, regards
